/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-05-03 17:52:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Modelo.*;
import java.util.*;
import ModeloDAO.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Modelo");
    _jspx_imports_packages.add("ModeloDAO");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>Needu</title>\r\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"estilos_indexx.css\">\r\n    <link rel=\"icon\" type=\"image/jpeg\" href=\"imagenes\\logo.jpeg\">\r\n    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+Meroitic&family=Poppins:wght@500&display=swap\" rel=\"stylesheet\">\r\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\">\r\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\">\r\n    \r\n<style>\r\n    .proa-tribu-container {\r\n        background-image: url('imagenes/fondo_unete.png');\r\n        background-size: cover;\r\n        background-position: center;\r\n        background-repeat: no-repeat;\r\n        padding: 50px 0; /* Ajusta este valor para la altura */\r\n        display: flex;\r\n        justify-content: flex-start; /* Alineación a la izquierda con espacio adicional */\r\n");
      out.write("        align-items: center;\r\n        text-align: left; /* Alinear texto a la izquierda */\r\n    }\r\n\r\n    .proa-tribu-content {\r\n        padding: 20px;\r\n        padding-left: 37%; /* Mantén tu padding izquierdo */\r\n        text-align: left; /* Alinear texto a la izquierda */\r\n    }\r\n\r\n    .proa-tribu-header img {\r\n        max-width: 120px; /* Aumenta el tamaño de tu imagen según prefieras */\r\n        margin-bottom: 20px; /* Espacio debajo de la imagen */\r\n    }\r\n\r\n    .proa-tribu-header h2 {\r\n        font-family: 'Poppins', sans-serif;\r\n        color: #000000; /* Color negro para 'Únete a la' */\r\n        font-size: 1.8rem; /* Tamaño de fuente */\r\n        margin: 5px 0; /* Menor separación entre los elementos */\r\n        text-align: left;\r\n    }\r\n\r\n    .proa-tribu-header h1 {\r\n        font-family: 'Poppins', sans-serif;\r\n        color: #4EC2A7; /* Color #4EC2A7 para 'Proa Tribu' */\r\n        font-size: 1.8rem; /* Tamaño de fuente igual para ambos */\r\n        margin: 5px 0; /* Menor separación entre los elementos */\r\n");
      out.write("        text-align: left;\r\n    }\r\n\r\n    .proa-tribu-content p {\r\n        color: #343a40;\r\n        font-size: 18px;\r\n        margin-top: 20px;\r\n        text-align: left; /* Alinear texto a la izquierda */\r\n        max-width: 600px; /* Limita el ancho de la descripción */\r\n        font-family: ScandiaWeb,sans-serif;\r\n    }\r\n    \r\n    \r\n    @media (max-width: 1200px) {\r\n        .proa-tribu-content {\r\n            padding-left: 20%; /* Ajusta este valor según sea necesario */\r\n        }\r\n    }\r\n    \r\n/* SECCIÓN DE TARJETAS */\r\n.ways-to-help-section {\r\n  background-color: #f9d1c5;\r\n  text-align: center;\r\n  padding: 50px 20px;\r\n}\r\n\r\n.ways-to-help-title {\r\n  color: #f1595c;\r\n  font-size: 2rem;\r\n  font-weight: bold;\r\n  margin: 0;\r\n  /* Asegura que los títulos estén en la misma línea */\r\n}\r\n\r\n/* Separación de las dos partes del subtítulo */\r\n.ways-to-help-subtitle {\r\n  color: #f1595c;\r\n  font-size: 2rem;\r\n  font-weight: bold;\r\n  margin: 0;\r\n  display: block; /* Ahora está en bloque para la separación */\r\n  padding-top: 0.5rem; /* Espacio adicional para 'que puedes ayudar de tres formas:' */\r\n");
      out.write("  padding-bottom: 60px;\r\n}\r\n\r\n.cards-container {\r\n  display: flex;\r\n  justify-content: center;\r\n  flex-wrap: wrap;\r\n  gap: 10px; /* Espacio reducido entre tarjetas */\r\n}\r\n\r\n.card {\r\n  background-color: #fff;\r\n  border-radius: 15px;\r\n  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n  padding: 30px 30px 120px; /* Padding incrementado en la parte inferior */\r\n  width: 250px;\r\n  margin: auto;\r\n  transition: transform 0.3s ease;\r\n  position: relative;\r\n  background-image: url('imagenes/manogracias.JPG');\r\n  background-position: center 343px; /* Posicionamiento de la imagen */\r\n  background-repeat: no-repeat;\r\n  background-size: 100% auto;\r\n  min-height: 290px; /* Altura mínima establecida */\r\n}\r\n\r\n.card:hover {\r\n  transform: translateY(-5px);\r\n}\r\n\r\n.card h3 {\r\n  margin-bottom: 20px;\r\n  font-size: 1.5rem;\r\n  color: #000; /* Títulos en negro */\r\n  font-weight: normal; /* Asegura que no estén en negrita */\r\n}\r\n\r\n.card h3 span {\r\n  color: #000000; /* Color para la parte específica del título */\r\n  font-weight: bold; /* Solo esta parte en negrita */\r\n");
      out.write("}\r\n\r\n.card p {\r\n  color: #666;\r\n  margin-bottom: 30px;\r\n  line-height: 1.6;\r\n}\r\n\r\n.card button {\r\n  background-color: #f1595c;\r\n  color: #fff;\r\n  border: none;\r\n  border-radius: 5px;\r\n  padding: 10px 20px;\r\n  cursor: pointer;\r\n  font-weight: bold;\r\n  transition: background-color 0.3s;\r\n}\r\n\r\n.card button:hover {\r\n  background-color: #c00;\r\n}\r\n\r\n/* Estilos para texto en negrita dentro de párrafos */\r\n.bold {\r\n  font-weight: bold;\r\n}\r\n\r\n\r\n/*QUE BENEFICIOS BRINDA*/\r\n.benefits-section {\r\n  text-align: center;\r\n  padding: 50px;\r\n  font-family: 'Poppins', sans-serif;\r\n  background-color: #ffffff; /* Fondo blanco para la sección */\r\n}\r\n\r\n.benefits-title {\r\n  color: #000;\r\n  margin-bottom: 20px;\r\n  font-size: 24px;\r\n  display: inline-block; /* Para que el h2 no ocupe el ancho completo */\r\n  position: relative; /* Para el posicionamiento de la pseudo-elemento */\r\n}\r\n\r\n.benefits-title::after {\r\n  content: ''; /* Se necesita para generar el pseudo-elemento */\r\n  display: block; /* Trata al pseudo-elemento como un bloque para que pueda tener ancho y alto */\r\n");
      out.write("  width: 100%; /* La barra roja se extiende a lo ancho del título */\r\n  height: 4px; /* Altura de la barra roja */\r\n  background-color: #f1595c; /* El color rojo de tu elección */\r\n  position: absolute; /* Posicionamiento absoluto respecto al título */\r\n  left: 0; /* Alinea la barra al lado izquierdo del título */\r\n  bottom: -10px; /* Posiciona la barra debajo del título */\r\n}\r\n\r\n.benefits-title span::after {\r\n  content: '';\r\n  display: block; /* Esto hace que el pseudo-elemento sea como un div debajo del span */\r\n  height: 4px; /* Altura de la barra roja */\r\n  background-color: #f1595c; /* El color rojo para la barra */\r\n  position: absolute; /* Posiciona la barra respecto al span */\r\n  left: 0;\r\n  right: 0;\r\n  bottom: 0; /* Justo debajo del texto */\r\n}\r\n\r\n\r\n\r\n.benefits-container {\r\n  display: flex;\r\n  justify-content: space-around;\r\n  flex-wrap: wrap;\r\n  max-width: 1200px; /* Ancho máximo para el contenedor */\r\n  margin: 0 auto; /* Centrar el contenedor en la página */\r\n  padding-top: 50px; /* Espacio superior añadido */\r\n");
      out.write("}\r\n\r\n.benefit {\r\n  width: 200px; /* O ajusta según sea necesario */\r\n  margin: 0 10px; /* Espacio horizontal para separar los elementos */\r\n  display: flex; /* Usar flexbox para centrar */\r\n  flex-direction: column; /* Orientar los elementos verticalmente */\r\n  align-items: center; /* Centrar elementos horizontalmente */\r\n}\r\n\r\n.benefit img {\r\n  width: 80%; /* Imágenes más pequeñas */\r\n  margin-bottom: 10px;\r\n}\r\n\r\n.benefit h3 {\r\n  color: #000;\r\n  font-size: 20px; /* Tamaño reducido para los subtítulos */\r\n  margin-bottom: 5px;\r\n}\r\n\r\n.benefit p {\r\n  color: #666;\r\n  font-size: 14px; /* Tamaño reducido para el párrafo */\r\n}\r\n\r\n/* Respuestas para pantallas más pequeñas */\r\n@media (max-width: 768px) {\r\n  .benefits-container {\r\n    flex-direction: column;\r\n    align-items: center;\r\n  }\r\n\r\n  .benefit {\r\n    width: 100%; /* Ocupa toda la anchura disponible */\r\n    max-width: 300px; /* Para evitar que las tarjetas sean demasiado anchas en pantallas más grandes */\r\n  }\r\n\r\n  .benefit img {\r\n    width: 60%; /* Imágenes aún más pequeñas para dispositivos móviles */\r\n");
      out.write("  }\r\n}\r\n\r\n\r\n\r\n</style>\r\n\r\n\r\n</head>\r\n<body>\r\n\r\n    <div id=\"navbar\">\r\n        <div class=\"logo\">NGO Volunteer</div>\r\n        <div class=\"menu-icon\" onclick=\"toggleMenu()\">\r\n            <img src=\"imagenes/menuU.png\" alt=\"Menú\">\r\n        </div>\r\n        <div class=\"links\">\r\n            <a href=\"Sobre_Nosotros.jsp\">Por qué ser voluntario</a>\r\n            <a href=\"ControladorLogin?accion=loginusuario\">Inicio de Sesión</a>\r\n            <a href=\"ControladorRegistro?accion=registro\" class=\"registro-btn\">Regístrate</a>\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div id=\"menu-options\" class=\"menu-options\">\r\n        <ul>\r\n            <li><a href=\"Sobre_Nosotros.jsp\">Por qué ser voluntario</a></li>\r\n            <li><a href=\"ControladorLogin?accion=loginusuario\">Inicio de Sesión</a></li>\r\n            <li><a href=\"ControladorRegistro?accion=registro\" class=\"registro-btn\">Regístrate</a></li>\r\n        </ul>\r\n    </div>\r\n\r\n    <div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"50\">\r\n        <div class=\"seccion\">\r\n");
      out.write("            <div class=\"fila\">\r\n                <div class=\"columna-mitad\">\r\n                    <div class=\"modulo texto fondo-claro\">\r\n                        <div class=\"texto-interior\"><h4>Voluntariado</h4></div>\r\n                    </div>\r\n                    <div class=\"modulo texto fondo-claro\">\r\n                        <div class=\"texto-interior\"><h1>Conviértete en voluntario o ayuda con un evento</h1></div>\r\n                    </div>\r\n                    <div class=\"modulo texto fondo-claro\">\r\n                        <div class=\"texto-interior\">\r\n                            <p>Vivamus eu sem et enim sagittis placerat quis et sem. Suspendisse imperdiet condimentum eleifend. Mauris tempus dignissim molestie. Quisque tempus aliquam.</p>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"modulo boton\">\r\n                        <a class=\"boton fondo-claro\" href=\"#\">Ponte en contacto</a>\r\n                    </div>\r\n                </div>\r\n                <div class=\"columna-mitad ultimo\">\r\n");
      out.write("                    <div class=\"modulo imagen\">\r\n                        <span class=\"imagen-contenedor\">\r\n                            <img decoding=\"async\" fetchpriority=\"high\" width=\"801\" height=\"801\" src=\"imagenes/doodle_index.png\" alt=\"doodle_index\" title=\"doodle_index\">\r\n                        </span>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    \r\n    <div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"50\">\r\n        <div class=\"seccion-cuadrados\">\r\n            <div class=\"cuadrado\" style=\"background-color: #EF8451;\">\r\n                <h2>Encuentra alguna oportunidad cerca de ti!</h2>\r\n                <button onclick=\"location.href='ControladorRegistro?accion=registro'\">Buscar</button>\r\n            </div>\r\n            <div class=\"cuadrado\" style=\"background-color: #264C4E;\">\r\n                <h2>Quieres volverte voluntario?</h2>\r\n                <button onclick=\"location.href='ControladorRegistro?accion=registro'\">Ponerse en Contacto</button>\r\n");
      out.write("            </div>\r\n        </div>\r\n    </div>\r\n    \r\n\r\n    <div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"100\">\r\n        <div class=\"proa-tribu-container\">\r\n          <div class=\"proa-tribu-content\">\r\n            <div class=\"proa-tribu-header\">\r\n              <img src=\"imagenes/unete.png\" alt=\"Icono\">\r\n              <h2>Únete a la</h2>\r\n              <h1>Comunidad NeedU</h1>\r\n            </div>\r\n            <p>La Comunidad NeedU es un grupo solidario comprometido con el cambio. A través de la colaboración de voluntarios y donantes, hemos impactado la vida de innumerables personas y apoyado a diversas organizaciones sociales en su misión.</p> \r\n          </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"50\">\r\n        <div class=\"ways-to-help-section\">\r\n            <h2 class=\"ways-to-help-title\">Ser de la Proa Tribu significa</h2>\r\n            <h2 class=\"ways-to-help-subtitle\">que puedes ayudar de tres formas:</h2>\r\n            <div class=\"cards-container\">\r\n");
      out.write("                <div class=\"card\">\r\n                    <h3><span>Quiero ser</span><br><span style=\"color: #4ec2a7;\">voluntario</span></h3>\r\n                    <p>Proa te <span class=\"bold\">conecta</span> con programas de voluntariado de <span class=\"bold\">más de 400</span> organizaciones sociales.<br> <span class=\"bold\">¡Elige la causa ideal para ti!</span></p>\r\n                    <button onclick=\"window.location.href='ControladorRegistro?accion=registro'\">Ser voluntario</button>\r\n                </div>\r\n                <div class=\"card\">\r\n                    <h3><span>Quiero</span><br><span style=\"color: #4ec2a7;\">apoyar</span></h3>\r\n                    <p>Conoce las formas en las que puedes apoyar a NeedU. <span class=\"bold\">Juntos</span> podemos marcar la <br> <span class=\"bold\">diferencia.</span></p>\r\n                    <button onclick=\"window.location.href='ControladorRegistro?accion=registro'\">Ser voluntario</button>\r\n                </div>\r\n                <div class=\"card\">\r\n                    <h3><span>Quiero</span><br><span style=\"color: #4ec2a7;\">aprender mas</span></h3>\r\n");
      out.write("                    <p>Explora nuestro sitio para obtener información adicional sobre NeedU, nuestra<span class=\"bold\">Mision</span>  y cómo puedes <span class=\"bold\">involucrarte</span>. en nuestra comunidad<span class=\"bold\"> solidaria.</span></p>\r\n                    <button onclick=\"window.location.href='ControladorRegistro?accion=registro'\">Más información</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"50\">\r\n        <div class=\"benefits-section\">\r\n          <h2 class=\"benefits-title\">¿Qué beneficios brinda la plataforma de NeedU?</h2>\r\n          <div class=\"benefits-container\">\r\n            <!-- Beneficio 1 -->\r\n            <div class=\"benefit\">\r\n              <img src=\"imagenes/beneficio1.png\" alt=\"Sencilla y Amigable\">\r\n              <h3>Sencilla y Amigable</h3>\r\n              <p>La plataforma es fácil de usar, rápida e intuitiva.</p>\r\n            </div>\r\n            <!-- Beneficio 2 -->\r\n            <div class=\"benefit\">\r\n");
      out.write("              <img src=\"imagenes/beneficio2.png\" alt=\"Confiable\">\r\n              <h3>Confiable</h3>\r\n              <p>Las organizaciones pasan por un filtro previo realizado Proa.</p>\r\n            </div>\r\n            <!-- Beneficio 3 -->\r\n            <div class=\"benefit\">\r\n              <img src=\"imagenes/beneficio3.png\" alt=\"Diversidad de causas\">\r\n              <h3>Diversidad de causas</h3>\r\n              <p>Tienes a tu disposición proyectos para donar según tu interés.</p>\r\n            </div>\r\n            <!-- Beneficio 4 -->\r\n            <div class=\"benefit\">\r\n              <img src=\"imagenes/beneficio4.png\" alt=\"Continuidad\">\r\n              <h3>Continuidad</h3>\r\n              <p>Damos seguimiento del proyecto para aumentar la transparencia.</p>\r\n            </div>\r\n          </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n    \r\n    \r\n<div class=\"wow animate__animated animate__fadeInDown\" data-wow-offset=\"50\">\r\n    <div class=\"faq-container\">\r\n        <div class=\"faq-section\">\r\n            <h2>Preguntas Frecuentes</h2>\r\n");
      out.write("            <div class=\"faq-item\">\r\n                <div class=\"faq-question\">\r\n                    <h3>¿Cómo puedo obtener reconocimiento por mi labor como voluntario en NeedU?</h3>\r\n                    <span class=\"faq-toggle\">▼</span>\r\n                </div>\r\n                <div class=\"faq-answer\">\r\n                    <p>En NeedU, valoramos y reconocemos la dedicación y el esfuerzo de nuestros voluntarios. Ofrecemos certificaciones y reconocimientos en base a tus contribuciones y logros en nuestra comunidad.</p>\r\n                </div>\r\n            </div>\r\n            <!-- Agrega una nueva pregunta aquí -->\r\n            <div class=\"faq-item\">\r\n                <div class=\"faq-question\">\r\n                    <h3>¿Existen programas de voluntariado a tiempo completo en NeedU que proporcionen apoyo financiero?</h3>\r\n                    <span class=\"faq-toggle\">▼</span>\r\n                </div>\r\n                <div class=\"faq-answer\">\r\n                    <p>Algunos de nuestros programas de voluntariado a tiempo completo en NeedU ofrecen estipendios para ayudar a cubrir los gastos de subsistencia durante tu servicio.</p>\r\n");
      out.write("                </div>\r\n            </div>\r\n            <!-- Continúa agregando preguntas según sea necesario -->\r\n            <div class=\"faq-item\">\r\n                <div class=\"faq-question\">\r\n                    <h3>¿Es posible hacer voluntariado desde casa con NeedU?</h3>\r\n                    <span class=\"faq-toggle\">▼</span>\r\n                </div>\r\n                <div class=\"faq-answer\">\r\n                    <p>Sí, en NeedU ofrecemos oportunidades de voluntariado que pueden realizarse de forma remota desde la comodidad de tu hogar.</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n    \r\n    <footer class=\"site-footer\">\r\n        <div class=\"footer-content\">\r\n            <div class=\"footer-section\">\r\n                <h4>Acerca de NEEDU</h4>\r\n                <p>AFS es una organización internacional, voluntaria, no gubernamental, sin fines de lucro, que promueve oportunidades de aprendizaje intercultural para ayudar a las personas a desarrollar el conocimiento, las destrezas y el entendimiento necesarios para crear un mundo más justo y pacífico.</p>\r\n");
      out.write("            </div>\r\n            <div class=\"footer-section\">\r\n                <h4>Contáctenos</h4>\r\n                <p>Para contactar a NEEDU Programas Interculturales Perú llámenos al: +51 976 359 635 o escríbanos al: +51 999 850 227.<br>\r\n                También puedes visitarnos en Av. Javier Prado Este 596 Of. 302. Tacna – Perú</p>\r\n            </div>\r\n            <div class=\"footer-section\">\r\n                <p>NEEDU apoya los Objetivos Mundiales de las Naciones Unidas</p>\r\n                <img src=\"imagenes/ods01.jpg\" alt=\"Objetivo de Desarrollo Sostenible 1\" />\r\n                <img src=\"imagenes/ods10.jpg\" alt=\"Objetivo de Desarrollo Sostenible 10\" />\r\n            </div>\r\n        </div>\r\n        <div class=\"footer-bottom\">\r\n            <p>&copy; NEEDU Perú 2023 | International Terms of Use & Policies | Política de cookies</p>\r\n        </div>\r\n    </footer>\r\n    \r\n    \r\n        <script>\r\n            document.querySelectorAll('.faq-question').forEach(question => {\r\n                question.addEventListener('click', () => {\r\n");
      out.write("                    const answer = question.nextElementSibling;\r\n                    const toggle = question.querySelector('.faq-toggle');\r\n\r\n                    answer.classList.toggle('open');\r\n                    toggle.classList.toggle('open');\r\n                });\r\n            });\r\n        </script>\r\n    \r\n\r\n    <script>\r\n        function toggleMenu() {\r\n            var menuOptions = document.getElementById(\"menu-options\");\r\n            if (menuOptions.style.display === \"none\" || menuOptions.style.display === \"\") {\r\n                menuOptions.style.display = \"block\";\r\n                setTimeout(function() {\r\n                    menuOptions.classList.add(\"active\");\r\n                }, 0);\r\n            } else {\r\n                menuOptions.classList.remove(\"active\"); // Retira la clase \"active\" para ocultar el menú\r\n                setTimeout(function() {\r\n                    menuOptions.style.display = \"none\"; // Oculta el menú después de que se retire la animación\r\n                }, 500); // Agrega un retraso para que la animación termine antes de ocultar el menú\r\n");
      out.write("            }\r\n        }\r\n\r\n        // Función para cerrar el menú cuando cambia el tamaño de la ventana\r\n        function closeMenuOnResize() {\r\n            var menuOptions = document.getElementById(\"menu-options\");\r\n            if (menuOptions.classList.contains('active')) {\r\n                menuOptions.classList.remove('active');\r\n                setTimeout(function() {\r\n                    menuOptions.style.display = \"none\";\r\n                }, 500);\r\n            }\r\n        }\r\n\r\n        // Agregar un controlador de eventos al evento 'resize' para detectar cambios de tamaño de ventana\r\n        window.addEventListener('resize', closeMenuOnResize);\r\n    </script>\r\n\r\n\r\n<script>\r\n    document.addEventListener('DOMContentLoaded', function () {\r\n        const elements = document.querySelectorAll('.custom-animation');\r\n\r\n        function isVisible(element) {\r\n            const rect = element.getBoundingClientRect();\r\n            const viewHeight = Math.max(document.documentElement.clientHeight, window.innerHeight);\r\n");
      out.write("            return !(rect.bottom < 0 || rect.top - viewHeight >= 0);\r\n        }\r\n\r\n        function scanDocument() {\r\n            elements.forEach(function (element) {\r\n                if (isVisible(element) && !element.classList.contains('animated')) {\r\n                    element.classList.add('animated', 'fadeInDown');\r\n                }\r\n            });\r\n        }\r\n\r\n        window.addEventListener('scroll', scanDocument);\r\n        scanDocument();\r\n    });\r\n</script>\r\n\r\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js\"></script>\r\n\r\n<script>\r\n  new WOW().init();\r\n</script>\r\n\r\n    \r\n    \r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
